In [1]:
import torch

In [2]:
M = torch.rand(1,3)
M

tensor([[0.5412, 0.7216, 0.7324]])

In [3]:
N = torch.rand(2,1)
N

tensor([[0.5612],
        [0.1680]])

In [4]:
#减法1
M-N

tensor([[-0.0200,  0.1604,  0.1711],
        [ 0.3732,  0.5536,  0.5644]])

In [5]:
#减法2
M.sub_(N)

RuntimeError: output with shape [1, 3] doesn't match the broadcast shape [2, 3]

In [6]:
#减法3
torch.sub(M,N)

tensor([[-0.0200,  0.1604,  0.1711],
        [ 0.3732,  0.5536,  0.5644]])

In [7]:
P = torch.normal(0,0.01,size=(3,2))

In [8]:
Q = torch.normal(0,0.01,size=(4,2))

In [9]:
Q = torch.transpose(Q,0,1)

In [10]:
Q.size()

torch.Size([2, 4])

In [11]:
print(P)
print(Q)

tensor([[ 0.0009, -0.0049],
        [ 0.0035,  0.0115],
        [-0.0249, -0.0159]])
tensor([[-0.0015,  0.0014, -0.0058, -0.0049],
        [-0.0048,  0.0100, -0.0049, -0.0146]])


In [12]:
torch.mm(P,Q)

tensor([[ 2.2114e-05, -4.8106e-05,  1.9422e-05,  6.7581e-05],
        [-6.0162e-05,  1.2029e-04, -7.7322e-05, -1.8560e-04],
        [ 1.1306e-04, -1.9269e-04,  2.2256e-04,  3.5428e-04]])

In [13]:
x=torch.tensor([1.0],requires_grad=True)

In [14]:
x

tensor([1.], requires_grad=True)

In [15]:
print(x.requires_grad)

True


In [16]:
y1 = x.pow(2)
y1.requires_grad_(True)

tensor([1.], grad_fn=<PowBackward0>)

In [17]:
with torch.no_grad():
    y2 = x.pow(3)

In [18]:
y3 = y1+y2
y3.requires_grad_(True)

tensor([2.], grad_fn=<AddBackward0>)

In [19]:
print(x.requires_grad)

True


In [20]:
y3.backward()

In [21]:
print(x.grad)

tensor([2.])


In [22]:
x.grad.data.zero_()

tensor([0.])